from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path

from omarchy_monitor_arrange.core.models import Monitor

DEFAULT_CONFIG_PATH = Path.home() / ".config" / "hypr" / "monitors.conf"


class HyprlandConfigWriter:
    """Reads/writes ~/.config/hypr/monitors.conf."""

    def __init__(self, path: Path = DEFAULT_CONFIG_PATH):
        self._path = path

    def write(self, monitors: list[Monitor], primary_name: str | None = None) -> None:
        ordered = list(monitors)
        if primary_name:
            ordered.sort(key=lambda m: m.name != primary_name)

        lines = [
            f"# Generated by omarchy-monitor-arrange on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]

        primary_scale = 1.0
        for m in ordered:
            if m.name == (primary_name or ordered[0].name):
                primary_scale = m.scale

        for m in ordered:
            mode = f"{m.width}x{m.height}@{m.refresh_rate:.0f}"
            pos = f"{m.x}x{m.y}"
            entry = f"monitor = {m.name}, {mode}, {pos}, {m.scale}"
            if m.transform != 0:
                entry += f", transform, {m.transform}"
            lines.append(entry)

        gdk_scale = max(1, min(2, int(primary_scale)))
        lines.append("")
        lines.append(f"env = GDK_SCALE,{gdk_scale}")
        lines.append("")

        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._path.write_text("\n".join(lines))

    def write_defaults(self) -> None:
        """Write the Hyprland default config: auto-detect all monitors."""
        lines = [
            f"# Reset to defaults by omarchy-monitor-arrange on "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "monitor = , preferred, auto, auto",
            "",
        ]
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._path.write_text("\n".join(lines))

    def backup(self) -> str | None:
        if not self._path.exists():
            return None
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = self._path.with_suffix(f".conf.bak.{ts}")
        shutil.copy2(self._path, backup_path)
        return str(backup_path)
